title: Lake County PASSAGE
icon: /assets/images/icon.png
author:
  name: Lake County PASSAGE
  email: passage@lakecountyil.gov

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Lake County PASSAGE provides real-time traffic information for Lake County, IL.

# Build settings

# If you clone the Minima repo and build locally, use this setting.
#theme: minima

# As of November 2023, GitHub Pages still uses Minima 2.5.1 (https://pages.github.com/versions/). 
# If you want to use the latest Minima version on GitHub Pages, use the following setting and 
# add a line comment on "theme: minima" above.
remote_theme: jekyll/minima

# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag

# Minima specific settings, which are only available from Minima 3.0 onward.
minima:
  # Minima skin selection.
  # Available skins are:
  # classic	           Default, light color scheme.
  # dark	             Dark variant of the classic skin.
  # auto	             Adaptive skin based on the default classic and dark skins.
  # solarized-light	   Light variant of solarized color scheme.
  # solarized-dark	   Dark variant of solarized color scheme.
  # solarized	         Adaptive skin for solarized color scheme skins.
  skin: classic

  # If you want to link only specific pages in the site-navigation, use this and list
  # the `path` property (as represented via Liquid) of the pages in the order they should
  # be rendered.
  nav_pages:
#    - about.md
    - privacy-policy.md
    - terms-and-conditions.md

  # Set to `true` to show excerpts on the homepage.
  #show_excerpts: false

  # Minima date format.
  # The default value is "%b %d, %Y" (e.g. Nov 14, 2023) 
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #date_format: "%b-%d-%Y"

  # Social Media Links
  # Renders icons via Font Awesome Free webfonts CDN, based on ordered list of entries.
  #
  # Entry keys:
  # * title    Tooltip rendered on hovering over icon.
  # * icon     Font Awesome icon id. `github` corresponds to `fa-github`.
  # * url      Full URL of social profile.
  social_links:
   - title: Github
     icon: github
     url: "https://github.com/lakecountypassage/smartphone-apps"
   - title: PASSAGE at X (formerly Twitter)
     icon: x-twitter
     url: "https://x.com/lcpassage"
   - title: Instagram
     icon: instagram
     url: "https://www.instagram.com/lakecountypassage"
   - title: Android App
     icon: google-play
     url: "https://play.google.com/store/apps/details?id=com.lakecountypassage&hl=en_US"
   - title: iOS App
     icon: app-store-ios
     url: "https://apps.apple.com/us/app/lake-county-passage/id417250237"